# Generated by Django 5.0 on 2023-12-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ap', models.CharField(max_length=20)),
                ('dni', models.IntegerField()),
                ('adhonoren', models.BooleanField()),
                ('sueldo', models.IntegerField()),
            ],
        ),
    ]
